// Archivo: /src/constants/summaryFields.js

export const SUMMARY_FIELD_LABELS = {
  estacionamiento_indebido: 'Estacionamiento Indebido',
  denuncias_trafico: 'Denuncias Tráfico',
  informes_trafico: 'Informes Tráfico',
  delitos_trafico: 'Delitos Seg. Vial',
  controles_trafico: 'Controles Tráfico',
  regulacion_trafico: 'Regulación Tráfico',
  deposito_vehiculos: 'Depósito Vehículos',
  diligencias_prevencion: 'Diligencias Prevención',
  otros_trafico: 'Otros (Tráfico)',
  contrap_patrimonio: 'Contra el Patrimonio',
  salud_publica: 'Contra la Salud Pública',
  denuncias_seguridad: 'Denuncias Seg. Ciudadana',
  identificaciones: 'Identificaciones',
  reyertas: 'Reyertas',
  violencia_genero: 'Violencia de Género',
  minutas: 'Minutas/Diligencias',
  detenidos_ciudadana: 'Detenidos',
  solicitud_datos_gc: 'Solicitud Datos GC',
  anomalias_via: 'Anomalías Vía Pública',
  vehiculos_abandonados: 'Vehículos Abandonados',
  denuncias_oomm: 'Denuncias O.O.M.M.',
  inspecciones_locales: 'Inspecciones Locales',
  inspecciones_obras: 'Inspecciones Obras',
  notificaciones: 'Notificaciones',
  informes_admin: 'Informes Administrativos',
  certificados_convivencia: 'Cert. Convivencia',
  auxilio_personas: 'Auxilio a Personas',
  fallecimientos: 'Fallecimientos',
  colab_bomberos: 'Colaboración Bomberos',
  colaboracion_gc: 'Colaboración GC',
  colab_sanitarios: 'Colaboración Sanitarios',
  intervencion_menores: 'Intervención Menores',
  req_ciudadanos: 'Requerimientos Ciudadanos',
  recepcion_llamadas: 'Recepción Llamadas',
  recepcion_denuncias: 'Recepción Denuncias',
  citaciones: 'Citaciones',
  diligencias_exposicion: 'Diligencias Exposición'
};

// Mapeo de nombres de Feather Icons
export const SUMMARY_FIELD_ICONS = {
  estacionamiento_indebido: 'MinusCircle',
  denuncias_trafico: 'Shield',
  informes_trafico: 'FileText',
  delitos_trafico: 'Octagon', // 'alert-octagon' en feather es Octagon con alerta o similar
  controles_trafico: 'BarChart2',
  regulacion_trafico: 'Move',
  deposito_vehiculos: 'Truck',
  diligencias_prevencion: 'Folder',
  otros_trafico: 'MoreHorizontal',
  contrap_patrimonio: 'Home',
  salud_publica: 'Activity',
  denuncias_seguridad: 'AlertCircle',
  identificaciones: 'Users',
  reyertas: 'UserX',
  violencia_genero: 'AlertTriangle',
  minutas: 'Edit',
  detenidos_ciudadana: 'UserCheck',
  solicitud_datos_gc: 'Share2',
  anomalias_via: 'Tool',
  vehiculos_abandonados: 'Truck',
  denuncias_oomm: 'Slash',
  inspecciones_locales: 'Coffee',
  inspecciones_obras: 'HardHat', // feather no tiene hard-hat, usaremos Tool o similar, o mapéalo a 'Tool' si falla
  notificaciones: 'Mail',
  informes_admin: 'File',
  certificados_convivencia: 'Award',
  auxilio_personas: 'Heart',
  fallecimientos: 'UserMinus',
  colab_bomberos: 'Wind',
  colaboracion_gc: 'UserPlus',
  colab_sanitarios: 'PlusCircle',
  intervencion_menores: 'User',
  req_ciudadanos: 'PhoneCall',
  recepcion_llamadas: 'Phone',
  recepcion_denuncias: 'Edit3',
  citaciones: 'Send',
  diligencias_exposicion: 'BookOpen'
};