// js/constants/summaryFields.js

// Definimos los campos en un solo lugar para que ambos módulos puedan importarlos.

export const SUMMARY_FIELD_LABELS = {
  estacionamiento_indebido: 'Estacionamiento Indebido',
  denuncias_trafico: 'Denuncias Tráfico',
  informes_trafico: 'Informes Tráfico',
  delitos_trafico: 'Delitos Seg. Vial',
  controles_trafico: 'Controles Tráfico',
  regulacion_trafico: 'Regulación Tráfico',
  deposito_vehiculos: 'Depósito Vehículos',
  diligencias_prevencion: 'Diligencias Prevención',
  otros_trafico: 'Otros (Tráfico)',
  contrap_patrimonio: 'Contra el Patrimonio',
  salud_publica: 'Contra la Salud Pública',
  denuncias_seguridad: 'Denuncias Seg. Ciudadana',
  identificaciones: 'Identificaciones',
  reyertas: 'Reyertas',
  violencia_genero: 'Violencia de Género',
  minutas: 'Minutas/Diligencias',
  detenidos_ciudadana: 'Detenidos',
  solicitud_datos_gc: 'Solicitud Datos GC',
  anomalias_via: 'Anomalías Vía Pública',
  vehiculos_abandonados: 'Vehículos Abandonados',
  denuncias_oomm: 'Denuncias O.O.M.M.',
  inspecciones_locales: 'Inspecciones Locales',
  inspecciones_obras: 'Inspecciones Obras',
  notificaciones: 'Notificaciones',
  informes_admin: 'Informes Administrativos',
  certificados_convivencia: 'Cert. Convivencia',
  auxilio_personas: 'Auxilio a Personas',
  fallecimientos: 'Fallecimientos',
  colab_bomberos: 'Colaboración Bomberos',
  colaboracion_gc: 'ColaborACIÓN GC',
  colab_sanitarios: 'Colaboración Sanitarios',
  intervencion_menores: 'Intervención Menores',
  req_ciudadanos: 'Requerimientos Ciudadanos',
  recepcion_llamadas: 'Recepción Llamadas',
  recepcion_denuncias: 'Recepción Denuncias',
  citaciones: 'Citaciones',
  diligencias_exposicion: 'Diligencias Exposición'
};

// Mueve también los iconos para mantener todo en un solo lugar
export const SUMMARY_FIELD_ICONS = {
  estacionamiento_indebido: 'minus-circle',
  denuncias_trafico: 'shield',
  informes_trafico: 'file-text',
  delitos_trafico: 'alert-octagon',
  controles_trafico: 'bar-chart-2',
  regulacion_trafico: 'move',
  deposito_vehiculos: 'truck',
  diligencias_prevencion: 'folder',
  otros_trafico: 'more-horizontal',
  contrap_patrimonio: 'home',
  salud_publica: 'activity',
  denuncias_seguridad: 'alert-circle',
  identificaciones: 'users',
  reyertas: 'user-x',
  violencia_genero: 'alert-triangle',
  minutas: 'edit',
  detenidos_ciudadana: 'user-check',
  solicitud_datos_gc: 'share-2',
  anomalias_via: 'tool',
  vehiculos_abandonados: 'truck',
  denuncias_oomm: 'slash',
  inspecciones_locales: 'coffee',
  inspecciones_obras: 'hard-hat',
  notificaciones: 'mail',
  informes_admin: 'file',
  certificados_convivencia: 'award',
  auxilio_personas: 'heart',
  fallecimientos: 'user-minus',
  colab_bomberos: 'wind',
  colaboracion_gc: 'user-plus',
  colab_sanitarios: 'plus-circle',
  intervencion_menores: 'user',
  req_ciudadanos: 'phone-call',
  recepcion_llamadas: 'phone',
  recepcion_denuncias: 'edit-3',
  citaciones: 'send',
  diligencias_exposicion: 'book-open'
};